In [ ]:
#Day 40 mini project 1
!pip install numpy

import numpy as np

# Create a 1D NumPy array with 12 random integers between 1 and 100
array_1d = np.random.randint(1, 101, size=12)
print("1D Array:\n", array_1d)

# Reshape the 1D array into a 4x3 matrix
array_2d = array_1d.reshape(4, 3)
print("\n2D Array (4x3):\n", array_2d)

# Extract the second row (index 1)
second_row = array_2d[1]
print("\nSecond row:", second_row)

# Extract the first column 
first_column = array_2d[:,0]
print("First column:", first_column)

# Extract the last two elements from the last row
last_two = array_2d[-1, -2:]
print("Last two elements of last row:", last_two)

# Print shape, size, and data type of the array
print("\nArray Shape:", array_2d.shape)
print("Array Size:", array_2d.size)
print("Array Data Type:", array_2d.dtype)



1D Array:
 [ 50  35   3  94  36  72  13  97  82 100  42  66]

2D Array (4x3):
 [[ 50  35   3]
 [ 94  36  72]
 [ 13  97  82]
 [100  42  66]]

Second row: [94 36 72]
First column: [ 50  94  13 100]
Last two elements of last row: [42 66]

Array Shape: (4, 3)
Array Size: 12
Array Data Type: int64
