In [ ]:
import numpy as np

#Steps:
#1. DataRepresentation:
#a. Create a 5x12 array representing the stock prices (in USD) for 5 stocks over 12 months (columns represent months, rows represent stocks).
#b. You can randomly generate the data using np.random.randint() to simulate stock prices between 100 and 500 USD.

np.random.seed(0)
stock_prices=np.random.randint(100,501,size=(5, 12))
print("Stock Prices:\n", stock_prices)


#2. Element-wiseOperations:
#a. Calculate the percentage change in stock prices from one month to the next for each stock using element-wise subtraction and division.
percentage_change = np.zeros_like(stock_prices, dtype=float)
percentage_change[:, 1:] = (stock_prices[:, 1:] - stock_prices[:, :-1]) / stock_prices[:, :-1] * 100
print("\nPercentage Change in Stock Prices:\n", percentage_change)

#3. Broadcasting:
#a. Subtracttheaveragestockpriceacrossallmonths(row-wise)from
#each stock's price (broadcast the mean to all elements).
row_mean = np.mean(stock_prices, axis=1, keepdims=True)
normalized = stock_prices - row_mean
print("\n📉 Normalized Prices:\n", np.round(normalized, 2))
#4. UniversalFunctions(ufunc):
#a. Usenp.sqrt()tocalculatethevolatility(standarddeviation)ofstock prices for each stock (apply to each row).
#b. Use np.exp() to simulate price growth over time for each stock.
#c. Apply np.log10() to determine the logarithmic scale of stock prices
#over time.
volatility = np.std(stock_prices, axis=1)
print("\n📈 Volatility (Std Dev):\n", np.round(volatility, 2))
#5. AggregationFunctions:
#a. Computethemeanandmedianstockpriceacrossallmonthsfor each stock using np.mean() and np.median().
#b. Find the maximum and minimum stock price across all months for each stock using np.max() and np.min().
#c. Calculate the variance and standard deviation to analyze price fluctuations across the months for each stock.
mean = np.mean(stock_prices, axis=1)
median = np.median(stock_prices, axis=1)
max_val = np.max(stock_prices, axis=1)
min_val = np.min(stock_prices, axis=1)

print("\n📌 Summary Stats:")
print("Average Price:", np.round(mean, 2))
print("Median Price:", median)
print("Max Price:", max_val)
print("Min Price:", min_val)


Stock Prices:
 [[272 147 217 292 423 351 295 459 109 311 377 342]
 [392 187 170 188 496 414 293 139 187 274 188 437]
 [265 125 433 172 365 215 343 297 435 438 199 277]
 [343 385 247 247 498 388 365 285 227 132 131 302]
 [344 251 263 470 283 128 390 228 228 153 489 138]]

Percentage Change in Stock Prices:
 [[  0.         -45.95588235  47.61904762  34.56221198  44.8630137
  -17.0212766  -15.95441595  55.59322034 -76.25272331 185.32110092
   21.22186495  -9.28381963]
 [  0.         -52.29591837  -9.09090909  10.58823529 163.82978723
  -16.53225806 -29.22705314 -52.55972696  34.5323741   46.52406417
  -31.38686131 132.44680851]
 [  0.         -52.83018868 246.4        -60.27713626 112.20930233
  -41.09589041  59.53488372 -13.41107872  46.46464646   0.68965517
  -54.56621005  39.1959799 ]
 [  0.          12.24489796 -35.84415584   0.         101.6194332
  -22.08835341  -5.92783505 -21.91780822 -20.35087719 -41.85022026
   -0.75757576 130.53435115]
 [  0.         -27.03488372   4.78087649  